# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, verbose_name='PRODUCT')),
                ('description', models.TextField(verbose_name='DESCRIPTION')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
