# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_post_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='seller',
        ),
    ]
