# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 07:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(11)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='schoolid',
            field=models.PositiveIntegerField(default=1, primary_key=True, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
