# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 11:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20160807_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.PositiveIntegerField(primary_key=True, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
