# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20160808_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='schoolid',
            field=models.PositiveIntegerField(primary_key=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
