# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 16:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20160817_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='schoolid',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
